### PR TITLE
fixed #51 : Click on an image to get a preview

### LINKED ISSUE #51: feature: click on an image to get a preview

### PR DESCRIPTION
**Pull request by Shashwat-111**
https://github.com/user-attachments/assets/26b2b4dc-c1c3-43f7-b442-99229e87759d

https://github.com/user-attachments/assets/f4bee9b0-d186-4e57-b39e-10156be44359

### CODE REVIEW

**Comment by csells** [comment]
excellent work. thank you very much.

**Comment by csells** [comment]
I did some minor refactoring. tell me what you think.

**Comment by Shashwat-111** [comment]
I am new to open source, so any feedback is much appreciated!

As I see from your refactor, is it better to create a separate class for dialogs rather than using top-level functions?

**Comment by csells** [comment]
The dialog class I found to be useful but it's a matter of personal taste. I tend to not like to make functions globally available (again, personal taste).

The bigger refactor was the addition of the _ImageAttachmentView as a parallel to _FileAttachmentView. I think the code came out a tiny bit easier to read doing that.

In general, however, your code was clean and worked great. No errors or warnings and all of the functionality was perfect. Thank you!

**Pull request merged**
